robot_size: 1.0 # [m] robot radius
sensor_range: 10.0 # [m] maximum observation range
N_SAMPLE: 10000  # number of sample_points

semantic_untraversable_class_list: [0, 2, 3, 5, 6, 7, 8]
final_untraversable_class_list: [0]
traversability_classes_cost: [99999, 0.6, 0.3, 0.1]

show_animation: True


WIDTH: 200    # [m]  map width
HEIGHT: 200    # [m]  map height
FEATURE_SIZE: 10.0 # [m] size of feature

n_bins: 5 # number of bins for the costmap
numOfClasses: 4 #n_bins - 1 # number of classes for the costmap


# numOfRegions: 40 # number of regions for the costmap
#numOfRegions = ceil(ceil(Width/FeatureSize)* 1.5))

p_certain: 0.95 # probability of the costmap being certain

traversability_objective: False

trials: 1
max_time: 5


generate_graph: True
demo: False

semantic_only: False


dem_file_path: "data/HO_P1_DEM.tif"
top_view_image_path: "data/HO_P1_DEM.png"
semantic_segmentation_mask_path: "data/HO_P1_DEM_mask_2.png"


# top_view_image_path: "data/small_colored_HO_P1_correct_scale.jpg"
# semantic_segmentation_mask_path: "data/small_HO_P1_mask_correct_scale.png"

N: 2000 # 750
N2: 1000

# N: 4000
# N2: 2000


